branche temporaire merge dev

diff --git a/.github/workflows/goodloc-workflow-prod.yml b/.github/workflows/goodloc-workflow-prod.yml
--- a/.github/workflows/goodloc-workflow-prod.yml
+++ b/.github/workflows/goodloc-workflow-prod.yml
@@ -1,15 +1,14 @@
-
-name: goodloc-workflow-dev-CI/CD
+name: goodloc-workflow-prod-CI/CD
 
 on:
   push:
     branches:
-      - goodloc_dev
+      - main
 
 jobs:
   build:
     runs-on: ubuntu-latest
-    environment: dev
+    environment: prod
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
@@ -25,7 +24,7 @@ jobs:
         with:
           context: .
           push: true
-          tags: ${{ secrets.DOCKERHUB_USERNAME }}/goodloc-dev:latest
+          tags: ${{ secrets.DOCKERHUB_USERNAME }}/goodloc24back:latest
           no-cache: true
 
   deploy:
@@ -53,8 +52,8 @@ jobs:
 
       - name: Copy docker-compose file to server
         run: |
-          scp -i ~/.ssh/id_rsagoodlocbck -o StrictHostKeyChecking=no docker-compose.dev.yml root@185.97.144.183:/GoodLoc24_backDev/docker-compose.dev.yml/docker-compose.dev.yml
-          ssh -i ~/.ssh/id_rsagoodlocbck -p 22 root@185.97.144.183 "ls -l /GoodLoc24_backDev/docker-compose.dev.yml/docker-compose.dev.yml"
+          scp -i ~/.ssh/id_rsagoodlocbck -o StrictHostKeyChecking=no docker-compose.prod.yml root@185.97.144.183:/GoodLoc24_backDev/docker-compose.prod.yml/docker-compose.prod.yml
+          ssh -i ~/.ssh/id_rsagoodlocbck -p 22 root@185.97.144.183 "ls -l /GoodLoc24_backDev/docker-compose.prod.yml/docker-compose.prod.yml"
         env:
           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
 
@@ -67,17 +66,17 @@ jobs:
           port: 22
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
-            if [ -f /GoodLoc24_backDev/docker-compose.dev.yml/docker-compose.dev.yml ]; then
-              echo "File /GoodLoc24_backDev/docker-compose.dev.yml/docker-compose.dev.yml found!"
-              cd /GoodLoc24_backDev/docker-compose.dev.yml
+            if [ -f /GoodLoc24_backDev/docker-compose.prod.yml/docker-compose.prod.yml ]; then
+              echo "File /GoodLoc24_backDev/docker-compose.prod.yml/docker-compose.prod.yml found!"
+              cd /GoodLoc24_backDev/docker-compose.prod.yml
               docker --version
               docker-compose --version
               docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
-              docker pull ${{ secrets.DOCKERHUB_USERNAME }}/goodloc-dev:latest
-              docker-compose -f docker-compose.dev.yml down || true
-              docker-compose -f docker-compose.dev.yml up -d
+              docker pull ${{ secrets.DOCKERHUB_USERNAME }}/goodloc24back:latest
+              docker-compose -f docker-compose.prod.yml down || true
+              docker-compose -f docker-compose.prod.yml up -d
             else
-              echo "File /GoodLoc24_backDev/docker-compose.dev.yml/docker-compose.dev.yml not found!"
+              echo "File /GoodLoc24_backDev/docker-compose.prod.yml/docker-compose.prod.yml not found!"
               exit 1
             fi
         env:
