nouvel essai deploiement

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -53,6 +53,7 @@ jobs:
       - name: Copy docker-compose file to server
         run: |
           scp -i ~/.ssh/id_rsagoodlocbck -o StrictHostKeyChecking=no docker-compose.prod.yml root@185.97.144.183:/GoodLoc24_backDev/docker-compose.prod.yml
+          ssh -i ~/.ssh/id_rsagoodlocbck -p 22 root@185.97.144.183 "ls -l /GoodLoc24_backDev/docker-compose.prod.yml"
         env:
           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
 
@@ -65,13 +66,18 @@ jobs:
           port: 22
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
-            mkdir -p /GoodLoc24_backDev
-            cd /GoodLoc24_backDev
-            docker --version
-            docker-compose --version
-            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
-            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/goodloc24back:latest
-            docker-compose -f docker-compose.prod.yml down || true
-            docker-compose -f docker-compose.prod.yml up -d
+            if [ -f /GoodLoc24_backDev/docker-compose.prod.yml ]; then
+              mkdir -p /GoodLoc24_backDev
+              cd /GoodLoc24_backDev
+              docker --version
+              docker-compose --version
+              docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
+              docker pull ${{ secrets.DOCKERHUB_USERNAME }}/goodloc24back:latest
+              docker-compose -f docker-compose.prod.yml down || true
+              docker-compose -f docker-compose.prod.yml up -d
+            else
+              echo "File /GoodLoc24_backDev/docker-compose.prod.yml not found!"
+              exit 1
+            fi
         env:
           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
